services:
  swagger-ui:
    container_name: letpai-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8089:8080"
    environment:
      SWAGGER_JSON: /mnt/swagger.yaml
    volumes:
      - ../../docs/swagger.yaml:/mnt/swagger.yaml:ro
