// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/letpai-backend/config"
	"github.com/glennprays/letpai-backend/domain/ports"
	"github.com/glennprays/letpai-backend/internal/handler"
	"github.com/glennprays/letpai-backend/internal/repository"
	"github.com/glennprays/letpai-backend/internal/router"
	"github.com/glennprays/letpai-backend/internal/service"
	"github.com/glennprays/letpai-backend/internal/usecase/auth"
	"github.com/glennprays/letpai-backend/internal/usecase/billing"
	"github.com/glennprays/letpai-backend/internal/usecase/contact"
	"github.com/glennprays/letpai-backend/internal/usecase/contactgroup"
	"github.com/glennprays/letpai-backend/internal/usecase/dashboard"
	"github.com/glennprays/letpai-backend/internal/usecase/notification"
	"github.com/glennprays/letpai-backend/internal/usecase/participant"
	"github.com/glennprays/letpai-backend/internal/usecase/payment"
	"github.com/glennprays/letpai-backend/internal/usecase/session"
	"github.com/glennprays/letpai-backend/pkg/logger"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApp creates the application and injects all dependencies
func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logLogger := logger.ProviderLogger(configConfig)
	db, err := NewPostgresConnection(configConfig)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	userRepository := repository.NewPostgresUserRepository(db)
	otpRepository := repository.NewPostgresOTPRepository(db)
	passwordService := NewPasswordService()
	otpService := NewOTPService(configConfig)
	whatsAppConfigRepository := repository.NewPostgresWhatsAppConfigRepository(db)
	whatsAppService := NewWhatsAppService(configConfig, whatsAppConfigRepository)
	registerUserUseCase := auth.NewRegisterUserUseCase(userRepository, otpRepository, passwordService, otpService, whatsAppService)
	jwtService := NewJWTService(configConfig)
	verifyOTPUseCase := auth.NewVerifyOTPUseCase(userRepository, otpRepository, jwtService, otpService)
	loginUserUseCase := auth.NewLoginUserUseCase(userRepository, passwordService, jwtService)
	logoutUserUseCase := auth.NewLogoutUserUseCase(jwtService)
	updateProfileUseCase := auth.NewUpdateProfileUseCase(userRepository)
	authHandler := handler.NewAuthHandler(registerUserUseCase, verifyOTPUseCase, loginUserUseCase, logoutUserUseCase, updateProfileUseCase)
	adminHandler := handler.NewAdminHandler()
	contactGroupRepository := repository.NewPostgresContactGroupRepository(db)
	createGroupUseCase := contactgroup.NewCreateGroupUseCase(contactGroupRepository)
	getGroupsUseCase := contactgroup.NewGetGroupsUseCase(contactGroupRepository)
	updateGroupUseCase := contactgroup.NewUpdateGroupUseCase(contactGroupRepository)
	deleteGroupUseCase := contactgroup.NewDeleteGroupUseCase(contactGroupRepository)
	contactGroupHandler := handler.NewContactGroupHandler(createGroupUseCase, getGroupsUseCase, updateGroupUseCase, deleteGroupUseCase)
	contactRepository := repository.NewPostgresContactRepository(db)
	createContactUseCase := contact.NewCreateContactUseCase(contactRepository, contactGroupRepository)
	getContactsUseCase := contact.NewGetContactsUseCase(contactRepository)
	getContactByIDUseCase := contact.NewGetContactByIDUseCase(contactRepository)
	updateContactUseCase := contact.NewUpdateContactUseCase(contactRepository, contactGroupRepository)
	deleteContactUseCase := contact.NewDeleteContactUseCase(contactRepository)
	bulkOperationsUseCase := contact.NewBulkOperationsUseCase(contactRepository, contactGroupRepository)
	importContactsUseCase := contact.NewImportContactsUseCase(contactRepository)
	contactHandler := handler.NewContactHandler(createContactUseCase, getContactsUseCase, getContactByIDUseCase, updateContactUseCase, deleteContactUseCase, bulkOperationsUseCase, importContactsUseCase)
	sessionRepository := repository.NewPostgresSessionRepository(db)
	createSessionUseCase := session.NewCreateSessionUseCase(sessionRepository)
	getSessionsUseCase := session.NewGetSessionsUseCase(sessionRepository)
	participantRepository := repository.NewPostgresParticipantRepository(db)
	billItemRepository := repository.NewPostgresBillItemRepository(db)
	getSessionDetailUseCase := session.NewGetSessionDetailUseCase(sessionRepository, participantRepository, billItemRepository)
	updateSessionUseCase := session.NewUpdateSessionUseCase(sessionRepository)
	cancelSessionUseCase := session.NewCancelSessionUseCase(sessionRepository)
	addParticipantsUseCase := participant.NewAddParticipantsUseCase(sessionRepository, participantRepository, contactRepository)
	removeParticipantUseCase := participant.NewRemoveParticipantUseCase(sessionRepository, participantRepository)
	updateParticipantUseCase := participant.NewUpdateParticipantUseCase(sessionRepository, participantRepository)
	addBillItemUseCase := billing.NewAddBillItemUseCase(sessionRepository, billItemRepository)
	updateBillItemUseCase := billing.NewUpdateBillItemUseCase(billItemRepository, sessionRepository)
	deleteBillItemUseCase := billing.NewDeleteBillItemUseCase(billItemRepository, sessionRepository)
	calculateSplitsUseCase := billing.NewCalculateSplitsUseCase(sessionRepository, participantRepository, billItemRepository)
	sessionHandler := handler.NewSessionHandler(createSessionUseCase, getSessionsUseCase, getSessionDetailUseCase, updateSessionUseCase, cancelSessionUseCase, addParticipantsUseCase, removeParticipantUseCase, updateParticipantUseCase, addBillItemUseCase, updateBillItemUseCase, deleteBillItemUseCase, calculateSplitsUseCase)
	imageService, err := NewImageServiceProvider(configConfig)
	if err != nil {
		return nil, err
	}
	submitPaymentUseCase := payment.NewSubmitPaymentUseCase(participantRepository, sessionRepository, imageService)
	approvePaymentUseCase := payment.NewApprovePaymentUseCase(participantRepository, sessionRepository)
	notificationLogRepository := repository.NewPostgresNotificationLogRepository(db)
	rejectPaymentUseCase := payment.NewRejectPaymentUseCase(participantRepository, sessionRepository, contactRepository, whatsAppService, notificationLogRepository)
	bulkApproveUseCase := payment.NewBulkApproveUseCase(participantRepository, sessionRepository)
	bulkRejectUseCase := payment.NewBulkRejectUseCase(participantRepository, sessionRepository, contactRepository, whatsAppService, notificationLogRepository)
	getPaymentPageUseCase := payment.NewGetPaymentPageUseCase(participantRepository, sessionRepository, billItemRepository, contactRepository)
	getPaymentProofUseCase := payment.NewGetPaymentProofUseCase(participantRepository)
	paymentHandler := handler.NewPaymentHandler(submitPaymentUseCase, approvePaymentUseCase, rejectPaymentUseCase, bulkApproveUseCase, bulkRejectUseCase, getPaymentPageUseCase, getPaymentProofUseCase)
	sendNotificationsUseCase := notification.NewSendNotificationsUseCase(sessionRepository, participantRepository, contactRepository, billItemRepository, whatsAppService, notificationLogRepository)
	client, err := NewRedisConnection(configConfig)
	if err != nil {
		return nil, err
	}
	rateLimitService := NewRateLimitService(client)
	sendReminderUseCase := notification.NewSendReminderUseCase(participantRepository, sessionRepository, contactRepository, whatsAppService, rateLimitService)
	bulkReminderUseCase := notification.NewBulkReminderUseCase(participantRepository, sessionRepository, contactRepository, whatsAppService, rateLimitService)
	notificationHandler := handler.NewNotificationHandler(sendNotificationsUseCase, sendReminderUseCase, bulkReminderUseCase)
	webhookHandler := handler.NewWebhookHandler(configConfig, notificationLogRepository)
	getDashboardUseCase := dashboard.NewGetDashboardUseCase(sessionRepository, participantRepository)
	dashboardHandler := handler.NewDashboardHandler(getDashboardUseCase)
	routerRouter := router.NewRouter(logLogger, healthHandler, authHandler, adminHandler, contactGroupHandler, contactHandler, sessionHandler, paymentHandler, notificationHandler, webhookHandler, dashboardHandler, jwtService, rateLimitService)
	app := &App{
		Config: configConfig,
		Logger: logLogger,
		DB:     db,
		Router: routerRouter,
	}
	return app, nil
}

// wire.go:

var CoreSet = wire.NewSet(config.Load, logger.ProviderLogger, NewPostgresConnection,
	NewRedisConnection,
)

var RepositorySet = wire.NewSet(repository.NewPostgresUserRepository, repository.NewPostgresOTPRepository, repository.NewPostgresContactGroupRepository, repository.NewPostgresContactRepository, repository.NewPostgresSessionRepository, repository.NewPostgresParticipantRepository, repository.NewPostgresBillItemRepository, repository.NewPostgresNotificationLogRepository, repository.NewPostgresWhatsAppConfigRepository, repository.NewPostgresAdminRepository)

var ServiceSet = wire.NewSet(
	NewJWTService,
	NewOTPService,
	NewPasswordService,
	NewWhatsAppService,
	NewImageServiceProvider,
	NewRateLimitService,
)

var UseCaseSet = wire.NewSet(auth.NewRegisterUserUseCase, auth.NewVerifyOTPUseCase, auth.NewLoginUserUseCase, auth.NewLogoutUserUseCase, auth.NewUpdateProfileUseCase, contact.NewCreateContactUseCase, contact.NewGetContactsUseCase, contact.NewGetContactByIDUseCase, contact.NewUpdateContactUseCase, contact.NewDeleteContactUseCase, contact.NewBulkOperationsUseCase, contact.NewImportContactsUseCase, contactgroup.NewCreateGroupUseCase, contactgroup.NewGetGroupsUseCase, contactgroup.NewUpdateGroupUseCase, contactgroup.NewDeleteGroupUseCase, session.NewCreateSessionUseCase, session.NewGetSessionsUseCase, session.NewGetSessionDetailUseCase, session.NewUpdateSessionUseCase, session.NewCancelSessionUseCase, participant.NewAddParticipantsUseCase, participant.NewRemoveParticipantUseCase, participant.NewUpdateParticipantUseCase, participant.NewImportFromGroupUseCase, billing.NewAddBillItemUseCase, billing.NewUpdateBillItemUseCase, billing.NewDeleteBillItemUseCase, billing.NewCalculateSplitsUseCase, payment.NewSubmitPaymentUseCase, payment.NewApprovePaymentUseCase, payment.NewRejectPaymentUseCase, payment.NewBulkApproveUseCase, payment.NewBulkRejectUseCase, payment.NewGetPaymentPageUseCase, payment.NewGetPaymentProofUseCase, notification.NewSendNotificationsUseCase, notification.NewSendReminderUseCase, notification.NewBulkReminderUseCase, dashboard.NewGetDashboardUseCase)

var HandlerSet = wire.NewSet(handler.NewHealthHandler, handler.NewAuthHandler, handler.NewAdminHandler, handler.NewContactGroupHandler, handler.NewContactHandler, handler.NewSessionHandler, handler.NewPaymentHandler, handler.NewNotificationHandler, handler.NewWebhookHandler, handler.NewDashboardHandler)

var ApiSet = wire.NewSet(
	HandlerSet, router.NewRouter,
)

// NewJWTService creates a new JWT service with config values
func NewJWTService(cfg *config.Config) *service.JWTService {
	return service.NewJWTService(
		cfg.JWTSecret,
		cfg.JWTExpiryHours,
	)
}

// NewOTPService creates a new OTP service with config values
func NewOTPService(cfg *config.Config) *service.OTPService {
	return service.NewOTPService(
		cfg.OTPExpiryMinutes,
	)
}

// NewPasswordService creates a new password service
func NewPasswordService() *service.PasswordService {
	return service.NewPasswordService(12)
}

// NewWhatsAppService creates a new WhatsApp service with config values
func NewWhatsAppService(cfg *config.Config, configRepo ports.WhatsAppConfigRepository) *service.WhatsAppService {
	return service.NewWhatsAppService(
		cfg.WhatsAppGatewayURL,
		cfg.WhatsAppAPIKey,
		configRepo,
	)
}

// NewImageService creates a new image service with AWS S3 configuration
func NewImageService(cfg *config.Config) (*service.ImageService, error) {
	imageCfg := &service.ImageConfig{
		AWSEndpoint: cfg.AWSEndpoint,
		AWSRegion:   cfg.AWSRegion,
		AWSAccessID: cfg.AWSAccessID,
		AWSSecret:   cfg.AWSSecret,
		BucketName:  cfg.S3BucketName,
		CDNURL:      cfg.CDNURL,
		EnableWebP:  cfg.EnableWebP,
		WebPQuality: cfg.WebPQuality,
		MaxFileSize: int64(cfg.MaxImageSizeMB) * 1024 * 1024,
	}
	return service.NewImageService(imageCfg)
}

// NewRateLimitService creates a new rate limit service with Redis client
func NewRateLimitService(redisClient *redis.Client) *service.RateLimitService {
	return service.NewRateLimitService(redisClient)
}

// NewImageServiceProvider creates a new image service provider that handles initialization errors
func NewImageServiceProvider(cfg *config.Config) (*service.ImageService, error) {
	return NewImageService(cfg)
}
