// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/letpai-backend/config"
	"github.com/glennprays/letpai-backend/internal/handler"
	"github.com/glennprays/letpai-backend/internal/router"
	"github.com/glennprays/letpai-backend/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logLogger := logger.ProviderLogger(configConfig)
	healthHandler := handler.NewHealthHandler()
	routerRouter := router.NewRouter(logLogger, healthHandler)
	app := &App{
		Config: configConfig,
		Logger: logLogger,
		Router: routerRouter,
	}
	return app, nil
}

// wire.go:

var CoreSet = wire.NewSet(config.Load, logger.ProviderLogger)

var ApiSet = wire.NewSet(handler.NewHealthHandler, router.NewRouter)
