// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/letpai-backend/config"
	"github.com/glennprays/letpai-backend/internal/handler"
	"github.com/glennprays/letpai-backend/internal/repository"
	"github.com/glennprays/letpai-backend/internal/router"
	"github.com/glennprays/letpai-backend/internal/service"
	"github.com/glennprays/letpai-backend/internal/usecase/auth"
	"github.com/glennprays/letpai-backend/internal/usecase/billing"
	"github.com/glennprays/letpai-backend/internal/usecase/contact"
	"github.com/glennprays/letpai-backend/internal/usecase/contactgroup"
	"github.com/glennprays/letpai-backend/internal/usecase/dashboard"
	"github.com/glennprays/letpai-backend/internal/usecase/notification"
	"github.com/glennprays/letpai-backend/internal/usecase/participant"
	"github.com/glennprays/letpai-backend/internal/usecase/payment"
	"github.com/glennprays/letpai-backend/internal/usecase/session"
	"github.com/glennprays/letpai-backend/pkg/logger"
)

func InitializeApp() (*App, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}
	log := logger.ProviderLogger(cfg)
	db, err := NewPostgresConnection(cfg)
	if err != nil {
		return nil, err
	}
	redisClient, err := NewRedisConnection(cfg)
	if err != nil {
		return nil, err
	}
	jwtSvc := service.NewJWTService(cfg.JWTSecret, cfg.JWTExpiryHours)
	otpSvc := service.NewOTPService(cfg.OTPExpiryMinutes)
	pwSvc := service.NewPasswordService(12)
	whatsappSvc := service.NewWhatsAppService(cfg.WhatsAppGatewayURL, cfg.WhatsAppAPIKey)
	imageCfg := &service.ImageConfig{
		AWSEndpoint: cfg.AWSEndpoint,
		AWSRegion:   cfg.AWSRegion,
		AWSAccessID: cfg.AWSAccessID,
		AWSSecret:   cfg.AWSSecret,
		BucketName:  cfg.S3BucketName,
		CDNURL:      cfg.CDNURL,
		EnableWebP:  cfg.EnableWebP,
		WebPQuality: cfg.WebPQuality,
		MaxFileSize: int64(cfg.MaxImageSizeMB) * 1024 * 1024,
	}
	imgSvc, err := service.NewImageService(imageCfg)
	if err != nil {
		return nil, err
	}
	rateLimitSvc := service.NewRateLimitService(redisClient)

	// Repositories
	userRepo := repository.NewPostgresUserRepository(db)
	otpRepo := repository.NewPostgresOTPRepository(db)
	contactGroupRepo := repository.NewPostgresContactGroupRepository(db)
	contactRepo := repository.NewPostgresContactRepository(db)
	sessionRepo := repository.NewPostgresSessionRepository(db)
	participantRepo := repository.NewPostgresParticipantRepository(db)
	billItemRepo := repository.NewPostgresBillItemRepository(db)
	notifLogRepo := repository.NewPostgresNotificationLogRepository(db)

	// Auth use cases
	registerUC := auth.NewRegisterUserUseCase(userRepo, otpRepo, pwSvc, otpSvc, whatsappSvc)
	verifyUC := auth.NewVerifyOTPUseCase(userRepo, otpRepo, jwtSvc, otpSvc)
	loginUC := auth.NewLoginUserUseCase(userRepo, pwSvc, jwtSvc)
	logoutUC := auth.NewLogoutUserUseCase(jwtSvc)
	updateProfileUC := auth.NewUpdateProfileUseCase(userRepo)

	// Contact group use cases
	createGroupUC := contactgroup.NewCreateGroupUseCase(contactGroupRepo)
	getGroupsUC := contactgroup.NewGetGroupsUseCase(contactGroupRepo)
	updateGroupUC := contactgroup.NewUpdateGroupUseCase(contactGroupRepo)
	deleteGroupUC := contactgroup.NewDeleteGroupUseCase(contactGroupRepo)

	// Contact use cases
	createContactUC := contact.NewCreateContactUseCase(contactRepo, contactGroupRepo)
	getContactsUC := contact.NewGetContactsUseCase(contactRepo)
	getContactByIDUC := contact.NewGetContactByIDUseCase(contactRepo)
	updateContactUC := contact.NewUpdateContactUseCase(contactRepo, contactGroupRepo)
	deleteContactUC := contact.NewDeleteContactUseCase(contactRepo)
	bulkOpsUC := contact.NewBulkOperationsUseCase(contactRepo, contactGroupRepo)
	importContactsUC := contact.NewImportContactsUseCase(contactRepo)

	// Session use cases
	createSessionUC := session.NewCreateSessionUseCase(sessionRepo)
	getSessionsUC := session.NewGetSessionsUseCase(sessionRepo)
	getSessionUC := session.NewGetSessionDetailUseCase(sessionRepo, participantRepo, billItemRepo)
	updateSessionUC := session.NewUpdateSessionUseCase(sessionRepo)
	cancelSessionUC := session.NewCancelSessionUseCase(sessionRepo)

	// Participant use cases
	addParticipantsUC := participant.NewAddParticipantsUseCase(sessionRepo, participantRepo, contactRepo)
	removeParticipantUC := participant.NewRemoveParticipantUseCase(sessionRepo, participantRepo)
	updateParticipantUC := participant.NewUpdateParticipantUseCase(sessionRepo, participantRepo)
	importFromGroupUC := participant.NewImportFromGroupUseCase(contactRepo, participantRepo)

	// Billing use cases
	addBillUC := billing.NewAddBillItemUseCase(sessionRepo, billItemRepo)
	updateBillUC := billing.NewUpdateBillItemUseCase(billItemRepo, sessionRepo)
	deleteBillUC := billing.NewDeleteBillItemUseCase(billItemRepo, sessionRepo)
	calcSplitsUC := billing.NewCalculateSplitsUseCase(sessionRepo, participantRepo, billItemRepo)

	// Payment use cases
	submitPayUC := payment.NewSubmitPaymentUseCase(participantRepo, sessionRepo, imgSvc)
	approvePayUC := payment.NewApprovePaymentUseCase(participantRepo, sessionRepo)
	rejectPayUC := payment.NewRejectPaymentUseCase(participantRepo, sessionRepo, contactRepo, whatsappSvc, notifLogRepo)
	bulkApprovePayUC := payment.NewBulkApproveUseCase(participantRepo, sessionRepo)
	bulkRejectPayUC := payment.NewBulkRejectUseCase(participantRepo, sessionRepo, contactRepo, whatsappSvc, notifLogRepo)
	getPayPageUC := payment.NewGetPaymentPageUseCase(participantRepo, sessionRepo, billItemRepo, contactRepo)
	getPayProofUC := payment.NewGetPaymentProofUseCase(participantRepo)

	// Notification use cases
	sendNotifUC := notification.NewSendNotificationsUseCase(sessionRepo, participantRepo, contactRepo, billItemRepo, whatsappSvc, notifLogRepo)
	sendReminderUC := notification.NewSendReminderUseCase(participantRepo, sessionRepo, contactRepo, whatsappSvc, rateLimitSvc)
	bulkReminderUC := notification.NewBulkReminderUseCase(participantRepo, sessionRepo, contactRepo, whatsappSvc, rateLimitSvc)

	// Dashboard use case
	getDashboardUC := dashboard.NewGetDashboardUseCase(sessionRepo, participantRepo)

	// Handlers
	healthHandler := handler.NewHealthHandler()
	authHandler := handler.NewAuthHandler(registerUC, verifyUC, loginUC, logoutUC, updateProfileUC)
	contactGroupHandler := handler.NewContactGroupHandler(createGroupUC, getGroupsUC, updateGroupUC, deleteGroupUC)
	contactHandler := handler.NewContactHandler(createContactUC, getContactsUC, getContactByIDUC, updateContactUC, deleteContactUC, bulkOpsUC, importContactsUC)
	sessionHandler := handler.NewSessionHandler(createSessionUC, getSessionsUC, getSessionUC, updateSessionUC, cancelSessionUC, addParticipantsUC, removeParticipantUC, updateParticipantUC, addBillUC, updateBillUC, deleteBillUC, calcSplitsUC)
	paymentHandler := handler.NewPaymentHandler(submitPayUC, approvePayUC, rejectPayUC, bulkApprovePayUC, bulkRejectPayUC, getPayPageUC, getPayProofUC)
	notificationHandler := handler.NewNotificationHandler(sendNotifUC, sendReminderUC, bulkReminderUC)
	webhookHandler := handler.NewWebhookHandler(cfg, notifLogRepo)
	dashboardHandler := handler.NewDashboardHandler(getDashboardUC)
	_ = importFromGroupUC

	// Router
	router := router.NewRouter(log, healthHandler, authHandler, contactGroupHandler, contactHandler, sessionHandler, paymentHandler, notificationHandler, webhookHandler, dashboardHandler, jwtSvc, rateLimitSvc)

	return &App{
		Config: cfg,
		Logger: log,
		DB:     db,
		Router: router,
	}, nil
}
